# Generated by Django 5.0.1 on 2024-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_expired',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
