# Generated by Django 5.0.2 on 2024-03-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_login_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
