# Generated by Django 5.0.1 on 2024-01-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class0', models.CharField(default='未分类0')),
                ('class1', models.CharField(default='未分类1')),
                ('ext0', models.CharField(default='')),
                ('ext1', models.CharField(default='')),
                ('ext2', models.CharField(default='')),
                ('ext3', models.CharField(default='')),
                ('ext4', models.CharField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='temp',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
