# Generated by Django 5.0.1 on 2024-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_alter_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FilePathField()),
                ('desc', models.TextField(default='')),
                ('url', models.URLField(default='./')),
                ('t', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
