# Generated by Django 5.0.1 on 2024-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='desc',
            new_name='remark',
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.CharField(default='demo.png'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(default='/'),
        ),
    ]
