# Generated by Django 5.0.1 on 2024-01-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_desc_banner_remark_alter_banner_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='BannerModel',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='0')),
                ('goodsname', models.CharField(default='-')),
                ('num', models.IntegerField(default=0)),
                ('saleprice', models.FloatField(default=0.0)),
                ('inputprice', models.FloatField(default=0.0)),
                ('brand', models.CharField(default='-')),
                ('remark', models.TextField(default='无')),
                ('t', models.DateTimeField(auto_now_add=True)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.categorymodel')),
            ],
        ),
    ]
