# Generated by Django 5.0.2 on 2024-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_goods_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='thumb',
            field=models.ImageField(default='', upload_to='goods'),
        ),
    ]
