# Generated by Django 5.0.1 on 2024-01-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_banner_bannermodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerModel',
            new_name='Banner',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='InventoryModel',
            new_name='Inventory',
        ),
    ]
