# Generated by Django 5.0.1 on 2024-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_bannermodel_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='img',
            field=models.CharField(default='goods_demo.png'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.CharField(default='banner_demo.png'),
        ),
    ]
