# Generated by Django 5.0.2 on 2024-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_goods_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='poster',
            field=models.ImageField(default='goods/kong.png', upload_to='goods/'),
        ),
    ]
