# Generated by Django 5.0.1 on 2024-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_inventory_img_alter_banner_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='classid',
            new_name='category',
        ),
    ]
