# Generated by Django 5.0.1 on 2024-01-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_keywords_alter_banner_remark_alter_category_ext0_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywords',
            table='keywords',
        ),
    ]
