# Generated by Django 5.0.1 on 2024-01-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_keywords_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywords',
            table='app1_keywords',
        ),
    ]
