# Generated by Django 5.0.1 on 2024-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_keywords_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='HotSearch',
        ),
        migrations.AlterModelTable(
            name='hotsearch',
            table=None,
        ),
    ]
