# Generated by Django 5.0.1 on 2024-01-27 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_keywords_hotsearch_alter_hotsearch_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable', models.FloatField(default=0.0)),
                ('t', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxname', models.CharField(default='匿名')),
                ('wxid', models.CharField(default='0')),
                ('name', models.CharField(default='匿名')),
                ('age', models.IntegerField(default='0')),
                ('tel', models.CharField(default='01234567890')),
                ('addr', models.CharField(default='-')),
                ('lastlogin', models.DateTimeField(auto_now=True)),
                ('t', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hotsearch',
            old_name='t',
            new_name='u',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('t', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bill')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
