# Generated by Django 5.0.1 on 2024-01-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_bill_user_rename_t_hotsearch_u_cart_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
