# Generated by Django 5.0.1 on 2024-01-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_bill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(default='/static/app1/category_demo.png'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.CharField(default='/static/app1/banner_demo.png'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img',
            field=models.CharField(default='/static/app1/goods_demo.png'),
        ),
    ]
